### PR TITLE
Xan/image renderer

### PR DESCRIPTION
**Pull request by XanthosXanthopoulos**

### CODE REVIEW

**Comment by SarantopoulosKon** [comment]
@XanthosXanthopoulos Let's enable uniformbuffers like we discussed for MacOS and remove any unused css rules

**Comment by SarantopoulosKon** [comment]
Issues i've noticed.

- Some warnings during build (mostly type issues)
- Zoom/Reset zoom controls don't work
```
[this.zoom...](gui-utils.ts:175 Uncaught TypeError: this.zoomCallback is not a function)
```
- The "Tile Image" example doesn't load the tiles looks idle for 1-2min. (See screenshots)
image
*Even though the UI states that it's loading 8 tiles, no requests are shown in the Network tab*

image
*First query starts at 1.9min*

**Comment by SarantopoulosKon** [comment]
Looks good overall, while working with storybook i see a "scene explorer" from babylonJS is it for debugging purposes? Do we need to disable it now? And lastly i think we should change the API, instead of `assetID` to set either `arrayID` or `groupID` so we avoid doing two requests to get metadata.
image

**Comment by XanthosXanthopoulos** [comment]
The debug layer should be disabled - I will update it shortly. As for the metadata fetching workflow I think it should be done in a follow up PR since this is already quite extensive.

**Review by SarantopoulosKon — APPROVED** [review]

**Pull request merged**
